<?php
	$failure = array (
		"I am error.",
		"An Error! Oh NOES!",
		"Only a penitent man will pass.",
		"I hate snakes.",
		"Hoot! Hoot!",
		"BAN KAI",
		"We are 99% sure its not our fault.",
		"The site is apparently doing its best Ronald Reagan impression.",
		"Please never ask me to do that again!",
		"The information you seek is lost in the tunnels of Cornett.",
		"In that and there.",
		"Follow the white rabbit...",
		"Support Mollie's.... CHEESEFRISES!",
		"Binge Responsibly.",
		"Ha! That one made me laugh.",
		"You might have more luck using YOUR username and password.",
		"Error detected between keyboard and chair.",
		"ITS destruction iminent. (We wish...)",
		"Watch OTB on select Wednesdays.",
		"Error: root login not supported!",
		"Be advisided the username '' and password '' are already taken.",
		"`/0|_| 4|23 |\|07 4 1337 |-| |-|4><0|2",
		"The universal aptitude for ineptitude makes any human accomplishment an incredible miracle.",
		"I have a bad feeling about this.",
		"There is no try, there is do or do not!",
		"Why didn't I take the blue pill?",
		"Did you forget your username or password?",
		"You have been denied.",
		"ACCESS DENIED",
		"You have failed!",
		"The cookie monster has the ring!",
		"I can't do that dave.",
		"Durrrr, whaddaya mean?",
		"Learn to type!",
		"Bad or missing mouse. Spank the cat? (Y/N)",
		"COFFEE.SYS missing... Insert cup in cup holder and press any key.",
		"Enter any 11-digit prime number to continue.",
		"Error reading FAT record. Try SKINNY one? (Y/N)",
		"File not found. Should I fake it? (Y/N)",
		"Invalid mouse movement.",
		"Press any key except... No, No, No, NOT THAT ONE!",
		"Press any key to continue or any other key to quit.",
		"Runtime Error 6D at 417A:32CF: Incompetent User.",
		"This is a message from God Gates: \"Reboot the world. Please log off.\"",
		"This will end your Windows session. Do you want to play another game?",
		"To \"shut down\" your system, type \"WIN\"",
		"User Error: Replace User.",
		"WinErr 16547: LPT1 not found. Use backup. (PENCIL&PAPER.SYS)",
		"Windows Message: \"Error saving file! Format drive now? (Y/Y)\"",
		"Windows VirusScan 1.0 - \"Windows found: Remove it? (Y/N)\"",
		"You don't exist. Go away.",
		"I refuse to debug myself!",
		"The error was not serious enough to justify halting the operation.",
		"Wrong! You cheating scum!",
		"Just what do you think you're doing Dave?",
		"It can only be attributed to human error.",
		"That's something I cannot allow to happen.",
		"My mind is going. I can feel it.",
		"Sorry about this, I know it's a bit silly.",
		"Take a stress pill and think things over.",
		"This mission is too important for me to allow you to jeopardize it.",
		"I feel much better now.",
		"No soap, honkie-lips.",
		"Where did you learn to type?",
		"Are you on drugs?",
		"My pet ferret can type better than you!",
		"You type like i drive.",
		"Do you think like you type?",
		"Your mind just hasn't been the same since the electro-shock, has it?",
		"Maybe if you used more than just two fingers...",
		"BOB says: You seem to have forgotten your passwd, enter another!",
		"stty: unknown mode: doofus",
		"I can't hear you -- I'm using the scrambler.",
		"The more you drive -- the dumber you get.",
		"Listen, burrito brains, I don't have time to listen to this trash.",
		"I've seen penguins that can type better than that.",
		"Have you considered trying to match wits with a rutabaga?",
		"You speak an infinite deal of nothing",
		"You silly, twisted boy you.",
		"He has fallen in the water!",
		"We'll all be murdered in our beds!",
		"You can't come in. Our tiger has got flu",
		"I don't wish to know that.",
		"What, what, what, what, what, what, what, what, what, what?",
		"You can't get the wood, you know.",
		"You'll starve!",
		"... and it used to be so popular...",
		"Pauses for audience applause, not a sausage",
		"Hold it up to the light --- not a brain in sight!",
		"Have a gorilla...",
		"There must be cure for it!",
		"There's a lot of it about, you know.",
		"You do that again and see what happens...",
		"Ying Tong Iddle I Po",
		"Harm can come to a young lad like that!",
		"And with that remarks folks, the case of the Crown vs yourself was proven.",
		"Speak English you fool --- there are no subtitles in this scene.",
		"You gotta go owwwww!",
		"I have been called worse.",
		"It's only your word against mine.",
		"I think ... err ... I think ... I think I'll go home",
		"Identity theft is a felony you know...",
		"What's the use of it all anyway?",
		"I think you ought to know I'm feeling very depressed.",
		"It won't work, I have an exceptionally large mind.",
		"All my life I've had this strange feeling that there's something big and sinister going on in the world.",
		"Wash your filthy hands!",
		"Life? Don't talk to me about life!",
		"It may disturb you. It scares the willies out of me.",
		"So long, so long and thanks for all the fish!",
		"Hey, that's not bad!",
		"That's a good answer...",
		"I'm sorry, did you just say you needed my brain?",
		"You're looking for the Ultimate Question.",
		"Your head a splode!",
		"You're the first person who's gotten that right. Everyone keeps calling me Santa.",
		"Well, I suppose the people who come to these parties are drunken idiots.",
		"Let us pray. Oh mighty one, we raise our noses to you blocked and unblown, send the handkerchief O blessed one that we may be wiped clean.",
		"It's an important and popular fact that things are not always what they seem. For instance, on the planet Earth, Man had always assumed that he was the most intelligent species occupying the planet, instead of the *third* most intelligent. The second most intelligent were of course dolphins. Dolphins had long known of the impending destruction of earth and had on many occasions tried to alert mankind but their warnings were mistakenly interpreted as amusing attempts to punch footballs or whistle for titbits.",
		"I want to go somewhere I've never been, and I'd like to go with you.",
		"You can't get ye flask!",
		"I'm certainly not going to tell thou!",
		"Oh, bollocks!",
		"What wouldst thou deau?",
		"Oh, bollocks!",
		"I'm a personality prototype. You can tell, can't you...?",
		"Curiously the only thing that went through the mind of the bowl of petunias, as it fell, was, 'Oh no, not again.'",
		"Apathetic bloody planet. I've no sympathy at all.",
		"Now you know that evil will always triumph because good is dumb.",
		"If there's anything around here more important than my ego, I want it caught and shot now!",
		"I checked The Guide for the best way to rescue a prisoner from Vogsphere, it said \"don't\".",
		"I am pleased to inform you that two nuclear missiles are now headed this way...",
		"Reply hazy, try again.",
		"My sources say no.",
		"Concentrate and ask again.",
		"Outlook not so good.",
		"Better not tell ya now",
		"I'm a robot. I'm not a refrigerator.",
		"Don't count on it.",
		"My reply is 'no'.",
		"Not that anyone cares what I think, but the restaurant is at the *other* end of the Universe.",
		"Wretched, isn't it?",
		"I'll handle this. I'm British. I know how to queue.",
		"Did you say the world is coming to an end? Shouldn't we all lie on the floor or put paper bags over our heads?",
		"Resistance is useless!",
		"You've got to know where your towel is.",
		"Who do you think I am, the governor of California?",
		"Is it secret, is it safe?",
		"Interesting. Even amongst my huge database of users... I couldn't find you.",
		"You know, I rather like this God fellow. Very theatrical, you know. Pestilence here, a plague there. Omnipotence ... gotta get me some of that.",
		"Nothing says \"Obey Me\" like a bloody head on a fence post!",
		"Victory is mine!",
		"I smell death on you.",
		"The ruptured capillaries in your nose belie the clarity of your wisdom."
	);
?>